# Generated by Django 4.2.5 on 2023-11-13 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySpaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("noise_level", models.IntegerField(default=1)),
                (
                    "available_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "start_hours",
                    models.TimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "end_hours",
                    models.TimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("lat", models.FloatField(default=38.0312)),
                ("lng", models.FloatField(default=-78.4989)),
                ("reservation", models.BooleanField(default=False)),
                ("location_details", models.CharField(max_length=255, null=True)),
                ("amenities", models.CharField(max_length=255, null=True)),
                ("maximum_occupancy", models.IntegerField(default=25, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "date_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("lat", models.FloatField(default=38.0312)),
                ("lng", models.FloatField(default=-78.4989)),
                ("reservation", models.BooleanField(default=False)),
                ("location_details", models.CharField(max_length=255, null=True)),
                ("incentives", models.CharField(max_length=255, null=True)),
                ("maximum_occupancy", models.IntegerField(default=25, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
